name: Auto Assign PR Author

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author-of-pr:
    uses: lluchkaa/actions/.github/workflows/auto-assign-pr.yaml@main
    secrets: inherit
