name: Assign Author

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    uses: lluchkaa/actions/.github/workflows/assign-author.yaml@4d7c90afededfbebb3b3779e071332f7aac08e1f # main
    secrets: inherit
