name: Assign Author

on:
  pull_request:
    types: [opened, reopened]
  issues:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    uses: lluchkaa/actions/.github/workflows/assign-author.yaml@455a26665880fe5b3b5ec3ce564effaa93d81c07 # main
    secrets: inherit
